id: IB08838A8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T07:14:20+00:00'
last_modified: '2022-06-08T08:46:51.556223+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23873
  title: ལམ་རིམ་མྱུར་ལམ་དང་ལམ་རིམ་བདེ་ལམ་གྱི་ཁྲིད་ཡིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    CFFA:
      image_group_id: I1KG12099
      title: ''
      total_pages: 651
      order: 1
      base_file: CFFA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
