id: P009122
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 19:24:02.312875
source_metadata:
  id: bdr:W23873
  title: ལམ་རིམ་མྱུར་ལམ་དང་ལམ་རིམ་བདེ་ལམ་གྱི་ཁྲིད་ཡིག
  author: ''
  volumes:
    a3da71266273496b9e319dc5d1f110b9:
      image_group_id: I1KG12099
      title: ''
      volume_number: 1
      total_pages: 651
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
